var FB_PUBLIC_LOAD_DATA_ = [null,[null,[[375392104,"NOME COMPLETO: ",null,0,[[65341417,null,1]
]
]
,[1148862115,"TURMA: ",null,2,[[282739118,[["E",null,null,null,0]
,["F",null,null,null,0]
,["G",null,null,null,0]
,["H",null,null,null,0]
]
,1,null,null,null,null,null,0]
]
]
,[576480493,"(ENEM 2013) O servo pertence à terra e rende frutos ao dono da terra. O operário urbano livre, ao contrário, vende-se a si mesmo e, além disso, por partes. Vende em leilão 8,10,12,15 horas da sua vida, dia após dia, a quem melhor pagar, ao proprietário das matérias-primas, dos instrumentos de trabalho e dos meios de subsistência, isto é, ao capitalista.MARX, K. Trabalho assalariado e capital \u0026 salário, preço e lucro. São Paulo: Expressão Popular, 2010.O texto indica que houve uma transformação dos espaços urbanos e rurais com a implementação do sistema capitalista, devido às mudanças tecnos sociais ligadas ao:",null,2,[[539654181,[["aumento populacional das cidades associado ao regime de servidão.",null,null,null,0]
,["aumento da produção rural, que fixou a população nesse meio.",null,null,null,0]
,["desenvolvimento da produção urbana associada às relações servis de trabalho.",null,null,null,0]
,["desenvolvimento das zonas urbanas e às novas relações de trabalho.",null,null,null,0]
,["desenvolvimento agrário e ao regime de servidão.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[1173961102,"(ENEM 2012) A imagem registra uma especificidade do contexto urbano em que a ausência ou ineficiência das políticas públicas resultou em:",null,2,[[684335257,[["superação do déficit habitacional.",null,null,null,0]
,["mediação dos conflitos entre classes.",null,null,null,0]
,["aumento da segregação socioespacial.",null,null,null,0]
,["garantia dos direitos humanos.",null,null,null,0]
,["controle da especulação imobiliária.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
,null,null,null,null,[["1XT1aBTAnXL69KDU_pBDeoCAsk2zapNL2VDaZ6FdECviS6A",null,[341,268,0]
]
]
]
,[686095755,"(ENEM - 2018)  O critério que rege a hierarquia urbana é a:",null,2,[[627892298,[["presença de sedes de multinacionais potencializando a conexão global.",null,null,null,0]
,["centralidade exercida por algumas cidades em relação às demais.",null,null,null,0]
,["importância histórica dos centros urbanos tradicionais.",null,null,null,0]
,["proximidade em relação ao litoral das principais cidades brasileiras.",null,null,null,0]
,["existência de distritos industriais de grande porte.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
,null,null,null,null,[["1y1LfU6jzA_RA-zq_NW8H6T-MPm80ZRz4SJ5TOozIE9iUQQ",null,[335,350,0]
]
]
]
,[621185872,"(ENEM 2017) A configuração do espaço urbano da região do Entorno do Distrito Federal assemelha-se às demais aglomerações urbanas e regiões metropolitanas do país, onde é facilmente identificável a constituição de um centro dinâmico e desenvolvido, onde se concentram as oportunidades de trabalho e os principais serviços, e a constituição de uma região periférica concentradora de população de baixa renda, com acesso restrito às principais atividades com capacidade de acumulação e produtividade, e aos serviços sociais e infraestrutura básica.(CAIADO, M. C. A migração intrametropolitana e o processo de estruturação do espaço urbano da Região Integrada de Desenvolvimento do Distrito Federal e Entorno. In: HOGAN, D. J. et al. (Org.). Migração e ambiente nas aglomerações urbanas. Campinas: Nepo/Unicamp, 2002.)A organização interna do aglomerado urbano descrito é resultado da ocorrência do processo de:",null,2,[[1454849709,[["polarização nacional.",null,null,null,0]
,["expansão vertical.",null,null,null,0]
,["segregação socioespacial.",null,null,null,0]
,["emancipação municipal.",null,null,null,0]
,["desregulamentação comercial.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[1402749503,"(ENEM 2015) O processo de concentração urbana no Brasil em determinados locais teve momentos de maior intensidade e, ao que tudo indica, atualmente passa por uma desaceleração no ritmo de crescimento populacional nos grandes centros urbanos.BAENINGER, R. Cidades e metrópoles: a desaceleração no crescimento populacional e novos arranjos regionais. Disponível em: www.sbsociologia.com.br. Acesso em: 12 dez. 2012 (adaptado).Uma causa para o processo socioespacial mencionado no texto é o(a)",null,2,[[2108716784,[["realocação da atividade industrial.",null,null,null,0]
,["centralização do poder político.",null,null,null,0]
,["carência de matérias-primas.",null,null,null,0]
,["aumento do crescimento vegetativo.",null,null,null,0]
,["degradação da rede rodoviária.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[1764918669,"(FGV-SP) Observe a imagem, que apresenta um fato comum encontrado em grande parte das médias e grandes cidades brasileiras na década de 1990. Decorridos mais de 10 anos entre o momento da foto e os dias atuais, pode-se afirmar que o planejamento urbano, no Brasil, é:",null,2,[[213929520,[["incipiente e inadequado porque não consegue corrigir as distorções criadas pelo crescimento desordenado.",null,null,null,0]
,["resultado do amadurecimento e mobilização da sociedade que reivindica melhorias na infraestrutura.",null,null,null,0]
,["uma realidade evidente que, de certo modo, consegue reduzir o apartheid urbano.",null,null,null,0]
,["considerado renovador porque está sempre transformando as áreas centrais das cidades.",null,null,null,0]
,["responsável por um rígido controle do crescimento urbano, via fiscalização do Estado.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
,null,null,null,null,[["1AKVEpTTeGHbwac5894kfkWTYYwHtDg8PJXt-pXVYXrSM4g",null,[300,156,0]
]
]
]
,[727388316,"Observe a letra da canção abaixo: Nas grandes cidades do pequeno dia a dia O medo nos leva a tudo, sobretudo a fantasia Então erguemos muros que nos dão a garantia De que morreremos cheios de uma vida tão vazia Nas grandes cidades de um país tão violento Os muros e as grades nos protegem de quase tudo Mas o quase tudo quase sempre é quase nada E nada nos protege de uma vida sem sentido (Engenheiros do Hawaii – “Muros e Grades”) Nos versos acima, há alguns apontamentos referentes a alguns problemas urbanos, dentre os quais podemos mencionar:",null,2,[[692595485,[["a violência urbana e o baixo padrão de vida sociocultural contemporâneo.",null,null,null,0]
,["a banalização da cultura televisiva especialmente exibida para a população das cidades.",null,null,null,0]
,["a crescente desorganização e descentralização das cidades.",null,null,null,0]
,["a violência familiar e o aumento de sequestros em domicílios.",null,null,null,0]
,["a onda de protestos que marcou o Brasil a partir de maio de 2013.",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[1112363136,"Na atual fase da urbanização mundial, podemos afirmar que os principais tipos de aglomerações urbanas atualmente existentes, ou seja, aquelas cidades que estão no topo da hierarquia urbana e que protagonizam a economia mundial são:",null,2,[[991136671,[["as metrópoles",null,null,null,0]
,["as cidades artificiais tecnológicas",null,null,null,0]
,["as cidades globais",null,null,null,0]
,["as regiões metropolitanas",null,null,null,0]
,["as cidades médias",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[1900157199,"O processo de urbanização ocorre a partir de fatores atrativos e repulsivos. Preencha a segunda coluna com base na primeira, identificando quais fenômenos enquadram-se nessas duas categorias mencionadas. A partir disso, assinale (1) para atores repulsivos e (2) para fatores atrativos. (   ) Concentração fundiária. (   ) Industrialização. (   ) Oferta de empregos urbanos. (   ) Modernização do meio rural.",null,2,[[368430783,[["1212",null,null,null,0]
,["1221",null,null,null,0]
,["2211",null,null,null,0]
,["1122",null,null,null,0]
,["2121",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
,[487098355,"(UFSCAR ) Com a acelerada urbanização da humanidade e o advento de gigantescas aglomerações urbanas, os especialistas no tema e as organizações internacionais logo criaram novos conceitos para dar conta dessas realidades. Dentre eles, existem os conceitos de megalópole, megacidade e cidade global.  A respeito desses conceitos, seria correto afirmar que: 1. Megalópole é uma gigantesca aglomeração urbana, com mais de 10 milhões de habitantes e onde há conurbação de inúmeras cidades vizinhas. 2. Cidade global é uma imensa área urbana com uma população de no mínimo 10 milhões de habitantes. 3. Megacidade é uma gigantesca aglomeração urbana com no mínimo 10 milhões de habitantes. 4. Megalópole é uma região superurbanizada onde, numa pequena extensão de um território nacional, se concentram várias cidades milionárias, que possuem uma vida econômica bastante interligada. São verdadeiras as afirmativas:",null,2,[[1272548229,[["1 e 2",null,null,null,0]
,["3 e 4",null,null,null,0]
,["2 e 3",null,null,null,0]
,["1 e 4",null,null,null,0]
,["2 e 4",null,null,null,0]
]
,1,null,null,null,null,null,1]
]
]
]
,["",0,0,0,0]
,null,null,[1,1]
,null,null,"3ª VC - GEOGRAFIA",48,[null,1]
,null,null,null,"pt_BR",[2]
,[[1,1,1,1,1]
,1,1]
]
,"/forms","Blank Quiz",null,null,null,"1",null,0,1,null,"Secretaria da Educação do Estado do Ceará",1,"e/1FAIpQLSfbY1641fZe5iMK_TL-u7Pt-rellcnbtYGd9gcZq7Ngyj9kEA",0,"[{\"data\":{\"value\":[]},\"keyPath\":[\"syncMap\",\"applicationFonts\",\"6\"],\"state\":{\"hashValue\":\"00000000\"}},{\"data\":{\"value\":[]},\"keyPath\":[\"syncMap\",\"domainFonts\",\"0\"],\"state\":{\"hashValue\":\"00000000\"}},{\"data\":{\"familyList\":[\"Alegreya\",\"Amatic SC\",\"Bree Serif\",\"Calibri\",\"Cambria\",\"Merriweather\",\"Permanent Marker\",\"Pinyon Script\",\"Playfair Display\",\"Proxima Nova\",\"Roboto\",\"Roboto Mono\",\"Ultra\",\"Varela Round\"],\"recentlyUsedFamilyList\":[],\"transitionedFamilyList\":[],\"hasTransitioned\":true},\"keyPath\":[\"syncMap\",\"preferences\",\"docs-fonts\"],\"state\":{\"timestamp\":1602178631781000}},{\"data\":{\"value\":0},\"keyPath…